add custom memory access calls
cs233/JsSpim pull request #10
Opened 2023-04-17 16:05 UTC by philvukovic

* change `MIPSImage::custom_memory_read` to return a `std::optional<mem_word>`
* add `MIPSImage::custom_memory_read` calls to `read_mem` functions
* add `MIPSImage::custom_memory_write` calls to `set_mem` functions

2023-04-17 19:34 UTC, Nydauron requested changes

2023-04-17 19:34 UTC, Nydauron commented on spim/CPU/mem.cpp
> +
MMIO addresses should expect reading/writing a word. It definitely complicates the logic if we include this one function for all 3 different reads/writes.

What you can do is add a virtual `custom_memory_read_word()`, `custom_memory_read_half()`, `custom_memory_read_byte()`, ... same for the custom writes. It still allows for the functionality of doing custom writes for half words and bytes, but doesnt interfere with our logic of word-only MMIOs.

2023-04-17 19:34 UTC, Nydauron commented on spim/CPU/mem.cpp
> +
Same as above comment

2023-04-17 19:34 UTC, Nydauron commented on spim/CPU/mem.cpp
> +
Same

2023-04-17 19:34 UTC, Nydauron commented on spim/CPU/mem.cpp
> +
Same

2023-04-27 16:28 UTC, philvukovic commented
should be good now

2023-04-27 19:06 UTC, Nydauron approved these changes

2023-04-27 19:07 UTC, merged