Added move constructor for `MIPSImage`
cs233/JsSpim pull request #13
Opened 2023-04-25 17:43 UTC by Nydauron

This PR adds a move constructor to `MIPSImage`.

There is some debate about whether to add a copy constructor (which would come in handy if we don't want to prepare the original assembly file, can technically (although seems rather inefficiently) allow the ability to rollback the state of the MIPS program to an earlier point in time).

Adding a copy constructor would require the use of `malloc()` to make sure that it is a deep copy rather than a shallow copy. It is sort of unclear as to what needs to be copied over as there are a lot of source pointers (pointers that were created by `malloc()`) and referential pointers (pointers that were shallow copied).

2023-04-26 06:05 UTC, philvukovic requested changes
changes look good. but from my understanding, a move assignment operator should also be implemented when we add a move constructor, so I would suggest we add that

2023-04-26 06:05 UTC, philvukovic commented on spim/CPU/image.h
> +    MIPSImage(MIPSImage&&);
A move assignment operator should also be implemented
`MIPSImage﻿& MIPSImage﻿﻿::operator=(MIPSImage﻿ ﻿&&)`

(and the copy assignment operator explicitly deleted as well)

https://en.cppreference.com/w/cpp/language/move_assignment

2023-04-26 06:05 UTC, philvukovic commented on spim/CPU/image_print_stream.h
> +        MIPSImagePrintStream(MIPSImagePrintStream&&);
A move assignment operator should also be implemented
MIPSImage﻿PrintStream& MIPSImage﻿﻿PrintStream::operator=(MIPSImagePrintStream﻿ ﻿&&)

https://en.cppreference.com/w/cpp/language/move_assignment

2023-04-26 06:09 UTC, philvukovic commented
> There is some debate about whether to add a copy constructor (which would come in handy if we don't want to prepare the original assembly file, can technically (although seems rather inefficiently) allow the ability to rollback the state of the MIPS program to an earlier point in time).

This could be added in the future if it's desired, but it doesn't seem necessary right now, and there are some potential complications in performing a full deep copy of the image

2023-04-26 17:20 UTC, Nydauron commented
> This could be added in the future if it's desired, but it doesn't seem necessary right now, and there are some potential complications in performing a full deep copy of the image. Move semantics fit the average use case better

Sg. Created issue #14

2023-04-26 22:21 UTC, Nydauron commented
Added assignment operators. Used the following code to test it:
```diff
diff --git a/spim/worker.cpp b/spim/worker.cpp
index 89fe55a..ea59df7 100644
--- a/spim/worker.cpp
+++ b/spim/worker.cpp
@@ -82,8 +82,10 @@ void reset(unsigned int max_contexts, std::set<unsigned int> &active_ctxs) {
         char file_name[64];
         sprintf(file_name, "./input_%d.s", i);
         if (read_assembly_file(new_image, file_name)) { // check if the file exists
-            new_image.reg_image().PC = starting_address(new_image);
-            ctxs.emplace(i, std::move(new_image));
+            MIPSImage img(i);
+            img = std::move(new_image);
+            img.reg_image().PC = starting_address(img);
+            ctxs.emplace(i, std::move(img));
         }
         yylex_destroy();
     }
```

Albeit it is rather inefficient, hence why its only being used for testing and not for production

For compiling for native, I also added the following to `main()` (mainly for the purposes of Valgrind):
```diff
diff --git a/main.cpp b/main.cpp
index d163359..417e703 100644
--- a/main.cpp
+++ b/main.cpp
@@ -1,2 +1,18 @@
 // Need to provide main() function for JsSpim to work
-int main() {}
+#include "spim/worker.h"
+#include <set>
+int main() {
+    std::set<unsigned int> active_ctxs({0, 1});
+
+    reset(2, active_ctxs);
+    reset(2, active_ctxs);
+    active_ctxs.clear();
+    active_ctxs.insert(1);
+    reset(2, active_ctxs);
+    active_ctxs.clear();
+    active_ctxs.insert(0);
+    reset(2, active_ctxs);
+    shutdown();
+
+    exit(0);
+}
```

2023-04-26 23:01 UTC, philvukovic requested changes
wanted some clarification on the change of `sink` from `&` to `*`. maybe this is fine for our use case, but it should be well-documented how the ostream is managed as it is a bit counter-intuitive

2023-04-26 23:01 UTC, philvukovic commented on spim/CPU/image_print_stream.h
> +        std::ostream *sink;
is there a good reason why this was changed to a pointer? it's not intuitive based on this API that we actually do 0 management of the `sink` object, which could cause programmer error in the future

should be changed or well-documented IMO

2023-04-26 23:27 UTC, Nydauron commented on spim/CPU/image_print_stream.h
> +        std::ostream *sink;
`std::ostream` copy constructor and copy assignement are both deleted; move constructor/assignment is protected so from a public scope, I can't say `this->sink = other.sink;`. Easy way to mitigate this is just to use a pointer. Note that it isn't unsafe due to the fact that if the original `std::ostream` goes out of scope, the `std::ostream &` type would also produce UB.

2023-04-27 16:03 UTC, philvukovic approved these changes

2023-04-27 16:03 UTC, philvukovic commented on spim/CPU/image_print_stream.h
> +        std::ostream *sink;
oh, I see. yeah, that checks out.

looks good to me then

2023-04-27 16:11 UTC, merged